SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes        # Audio control and System control
CAPS_WORD_ENABLE = yes
REPEAT_KEY_ENABLE = yes
LTO_ENABLE = yes
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
AUDIO_ENABLE = no           # Audio output
NKRO_ENABLE = yes
CONSOLE_ENABLE = no         # Console for debug
COMMAND_ENABLE = no         # Commands for debug and configuration
BOOTMAGIC_ENABLE = no       # Enable Bootmagic Lite
RGBLIGHT_ENABLE = no       # Enable WS2812 RGB underlight.
SWAP_HANDS_ENABLE = no      # Enable one-hand typing
RAW_ENABLE = yes     # If you want to enable lang switching feature
MAGIC_ENABLE = no
COMBO_ENABLE = no
SRC += queyenth.c callum.c companion.c
